### ISSUE TITLE
can you upload TNT inference code ?

### ISSUE THREAD

**Issue by alexliyang** [huawei-noah/CV-Backbones#70]
can you upload tnt's inference code?

**Comment by iamhankai** [comment]
The inference code is included in train.py.

inference example:

`python train.py /path/to/imagenet/ --model tnt_s_patch16_224 -b 256 --pretrain_path /path/to/pretrained/model/ --evaluate
`

**Comment by JohnsonZ-microe** [comment]
I ran with the code but faced an error. :(

Traceback (most recent call last):
  File "train.py", line 35, in <module>
    from timm.data import Dataset, resolve_data_config, Mixup, FastCollateMixup, AugMixDataset #, create_loader
ImportError: cannot import name 'Dataset' from 'timm.data' (D:\Anaconda\Anaconda\lib\site-packages\timm\data\__init__.py)

**Comment by iamhankai** [comment]
Use timm 0.3.2 please.

**Comment by JohnsonZ-microe** [comment]
I just tried this solution, now the previous error disappeared but came with a new one. 

Traceback (most recent call last):
  File "train.py", line 35, in <module>
    from timm.data import Dataset, resolve_data_config, Mixup, FastCollateMixup, AugMixDataset #, create_loader
  File "D:\Anaconda\Anaconda\lib\site-packages\timm\__init__.py", line 2, in <module>
    from .models import create_model, list_models, is_model, list_modules, model_entrypoint, \
  File "D:\Anaconda\Anaconda\lib\site-packages\timm\models\__init__.py", line 1, in <module>
    from .cspnet import *
  File "D:\Anaconda\Anaconda\lib\site-packages\timm\models\cspnet.py", line 20, in <module>
    from .helpers import build_model_with_cfg
  File "D:\Anaconda\Anaconda\lib\site-packages\timm\models\helpers.py", line 17, in <module>
    from .layers import Conv2dSame, Linear
  File "D:\Anaconda\Anaconda\lib\site-packages\timm\models\layers\__init__.py", line 7, in <module>
    from .cond_conv2d import CondConv2d, get_condconv_initializer
  File "D:\Anaconda\Anaconda\lib\site-packages\timm\models\layers\cond_conv2d.py", line 16, in <module>
    from .helpers import to_2tuple
  File "D:\Anaconda\Anaconda\lib\site-packages\timm\models\layers\helpers.py", line 6, in <module>
    from torch._six import container_abcs
ImportError: cannot import name 'container_abcs' from 'torch._six' (C:\Users\11351\AppData\Roaming\Python\Python38\site-packages\torch\_six.py)

I guess there is something wrong with the conflict between different versions of Pytorch and timm, could you please provide the version of your pytorch?

**Comment by iamhankai** [comment]
pytorch 1.7.0

**Comment by goodmorningsi** [comment]
> I ran with the code but faced an error. :(
> 
> Traceback (most recent call last): File "train.py", line 35, in from timm.data import Dataset, resolve_data_config, Mixup, FastCollateMixup, AugMixDataset #, create_loader ImportError: cannot import name 'Dataset' from 'timm.data' (D:\Anaconda\Anaconda\lib\site-packages\timm\data__init__.py)

Hello, I have meet the same problem,  if you solved this problem？
